# Generated by Django 5.0.3 on 2024-04-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('fathername', models.CharField(max_length=1000)),
                ('classname', models.IntegerField()),
                ('contact', models.CharField(max_length=1000)),
            ],
        ),
    ]
